#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8
awk '{if($2=="localhost") $1="127.0.0.2"; print}' /etc/hosts > /tmp/hosts_new
cat /tmp/hosts_new > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
